name: my_new_project
version: 1.0.0
config-version: 2
profile: pg
source-paths:
  - "models"
analysis-paths:
  - "analysis"
test-paths:
  - "tests"
data-paths:
  - "data"
macro-paths:
  - "macros"
snapshot-paths:
  - "snapshots"
target-path: "target"
clean-targets:
  - target
  - dbt_modules
models: #all models here
  my_new_project:
    analytics:
      materialized: view
      #random tag
      customer_film_categories:
        +tags:
          - film
          - film
          - views
          - promoted
      film_category_name:
        +tags:
          - film
          - category
      #other random tag
      customer_categories:
        tags:
          - category
          - demoted
      customer_address:
        tags:
          - film
          - films
          - promoted





