version: 2
models:
  - name: film_category_name
    description: "Film Category Name - rolled up from master category list\_\_"
    columns:
      - name: title
        description: Film Category Title
      - name: description
        description: Film Category Description
      - name: film_id
        description: ID to Film table
      - name: category_name
        description: ''
  - name: customer_categories
    columns:
      - name: customer_name
        description: Customer Name (concat of First Name and Last Name)
      - name: rental_count
        description: >-
          Total number of times a customer has rented from us. Not to be
          mistaken for total number of DVDs rented.
      - name: category_name
        description: ''
    description: Customer Categories final model
  - name: customer_address
    columns:
      - name: first_name
        description: First name of the customer.
      - name: last_name
        description: Last name of the customer.
      - name: last_name123
        description: Last name
      - name: customer_id
        description: ID of the customer
    description: Customer Address intermediate model
