version: 2
models:
  - name: film_category_name
    description: asdf
    columns:
      - name: title
        description: adsofiaasdfdsf
  - name: customer_categories
    columns:
      - name: customer_name
        description: ''
    description: >-
      This model does not yet have a description. In future releases, this will
      be editable here.
  - name: customer_address
    columns:
      - name: first_name
        description: First name of the customer
      - name: last_name
        description: ''
    description: >-
      This model does not yet have a description. In future releases, this will
      be editable here.
