version: 2
models:
  - name: film_category_name
    description: asdf
    columns:
      - name: title
        description: adsofiaasdfdsf
  - name: customer_categories
    columns:
      - name: customer_name
        description: ''
      - name: rental_count
        description: >-
          Total number of times a customer has rented from us. Not to be
          mistaken for total number of DVDs rented.
      - name: category_name
        description: ''
    description: Customer Categories final model
  - name: customer_address
    columns:
      - name: first_name
        description: First name of the customer.
      - name: last_name
        description: Last name of the customer.
      - name: last_name123
        description: Last name
    description: Customer Address intermediate model
