version: 2
sources:
  - name: public
    description: The dvdrental dummy database
    tables:
      - name: actor
      - name: address
      - name: category
      - name: city
      - name: country
        columns:
          - name: country_id
            description: Column 1 - renamed 3 times
          - name: country
            description: Column 2 - renamed five times
          - name: last_update
            description: |-
              Column 3 - using" special$$&!*(&!@(*&#$)%asdf characters

              and newlines


              and more newlines

              and powershell injections; Write-Host "it escaped!"
        description: Description works; powershell injection does not
      - name: customer
      - name: film
        columns:
          - name: film_id
            description: ''
          - name: title
            description: ''
          - name: release_year
            description: "the year\_"
      - name: film_actor
      - name: film_category
      - name: inventory
      - name: language
      - name: payment
      - name: rental
      - name: staff
      - name: store
